import pandas as pd
import numpy as np

df = pd.read_csv('C:/Users/hariv/Downloads/files/hospital_project/diabetic_data.csv')

print("=== MISSING VALUES (including ?) ===")
for col in df.columns:
    null_count = int(df[col].isna().sum())
    q_count = int((df[col] == '?').sum()) if df[col].dtype == object else 0
    total_missing = null_count + q_count
    pct = round(total_missing / len(df) * 100, 2)
    if total_missing > 0:
        print(f"{col}: null={null_count}, ?={q_count}, total={total_missing} ({pct}%)")

print()
print("=== TARGET: readmitted ===")
print(df['readmitted'].value_counts())
print()
print("=== AGE ===")
print(df['age'].value_counts().sort_index())
print()
print("=== GENDER ===")
print(df['gender'].value_counts())
print()
print("=== RACE ===")
print(df['race'].value_counts())
print()
print("=== WEIGHT (top values) ===")
print(df['weight'].value_counts().head(15))
print()
print("=== change ===")
print(df['change'].value_counts())
print()
print("=== diabetesMed ===")
print(df['diabetesMed'].value_counts())
print()
print("=== DUPLICATES ===")
print("Duplicate encounter_id:", df['encounter_id'].duplicated().sum())
print("Duplicate patient_nbr:", df['patient_nbr'].duplicated().sum())
print()
print("=== time_in_hospital stats ===")
print(df['time_in_hospital'].describe())
print()
print("=== num_medications stats ===")
print(df['num_medications'].describe())
print()
print("=== number_diagnoses stats ===")
print(df['number_diagnoses'].describe())
print()
print("=== medical_specialty top 20 ===")
print(df['medical_specialty'].value_counts().head(20))
print()
print("=== discharge_disposition_id unique ===")
print(sorted(df['discharge_disposition_id'].unique()))
print()
print("=== number_emergency stats ===")
print(df['number_emergency'].describe())
print()
print("=== number_outpatient stats ===")
print(df['number_outpatient'].describe())
print()
print("=== number_inpatient stats ===")
print(df['number_inpatient'].describe())
